(cl:in-package mobrob_util-msg)
(cl:export '(E0RADIANS-VAL
          E0RADIANS
          E1RADIANS-VAL
          E1RADIANS
          E0METERS-VAL
          E0METERS
          E1METERS-VAL
          E1METERS
          E0RADPERSEC-VAL
          E0RADPERSEC
          E1RADPERSEC-VAL
          E1RADPERSEC
          E0METERSPERSEC-VAL
          E0METERSPERSEC
          E1METERSPERSEC-VAL
          E1METERSPERSEC
          A0-VAL
          A0
          A1-VAL
          A1
          A2-VAL
          A2
          A3-VAL
          A3
          A4-VAL
          A4
          A5-VAL
          A5
          U0METERS-VAL
          U0METERS
          U1METERS-VAL
          U1METERS
          U2METERS-VAL
          U2METERS
          DT-VAL
          DT
))