// Generated by gencpp from file mobrob_util/ME439WheelSpeeds.msg
// DO NOT EDIT!


#ifndef MOBROB_UTIL_MESSAGE_ME439WHEELSPEEDS_H
#define MOBROB_UTIL_MESSAGE_ME439WHEELSPEEDS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mobrob_util
{
template <class ContainerAllocator>
struct ME439WheelSpeeds_
{
  typedef ME439WheelSpeeds_<ContainerAllocator> Type;

  ME439WheelSpeeds_()
    : v_left(0.0)
    , v_right(0.0)  {
    }
  ME439WheelSpeeds_(const ContainerAllocator& _alloc)
    : v_left(0.0)
    , v_right(0.0)  {
  (void)_alloc;
    }



   typedef float _v_left_type;
  _v_left_type v_left;

   typedef float _v_right_type;
  _v_right_type v_right;





  typedef boost::shared_ptr< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> const> ConstPtr;

}; // struct ME439WheelSpeeds_

typedef ::mobrob_util::ME439WheelSpeeds_<std::allocator<void> > ME439WheelSpeeds;

typedef boost::shared_ptr< ::mobrob_util::ME439WheelSpeeds > ME439WheelSpeedsPtr;
typedef boost::shared_ptr< ::mobrob_util::ME439WheelSpeeds const> ME439WheelSpeedsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator1> & lhs, const ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator2> & rhs)
{
  return lhs.v_left == rhs.v_left &&
    lhs.v_right == rhs.v_right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator1> & lhs, const ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobrob_util

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db3ff789940b54ebf58420f0dabd5157";
  }

  static const char* value(const ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb3ff789940b54ebULL;
  static const uint64_t static_value2 = 0xf58420f0dabd5157ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobrob_util/ME439WheelSpeeds";
  }

  static const char* value(const ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 v_left\n"
"float32 v_right\n"
;
  }

  static const char* value(const ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v_left);
      stream.next(m.v_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ME439WheelSpeeds_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobrob_util::ME439WheelSpeeds_<ContainerAllocator>& v)
  {
    s << indent << "v_left: ";
    Printer<float>::stream(s, indent + "  ", v.v_left);
    s << indent << "v_right: ";
    Printer<float>::stream(s, indent + "  ", v.v_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBROB_UTIL_MESSAGE_ME439WHEELSPEEDS_H
